# Generated by Django 3.0.1 on 2020-02-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('following', models.TextField()),
                ('followers', models.CharField(max_length=40)),
                ('image_avaliable', models.BooleanField(default=True)),
            ],
        ),
    ]
