# Generated by Django 3.0.1 on 2020-02-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.TextField(),
        ),
    ]
